name: epson_epos
description: Epson ePOS SDK for Flutter
version: 0.0.1+4
repository: https://github.com/ImTung/flutter_epson_epos
homepage: https://github.com/ImTung/flutter_epson_epos

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tlt.epson_epos
        pluginClass: EpsonEposPlugin
      ios:
        pluginClass: EpsonEposPlugin
