name: epson_epos
description: This plugin allows Flutter apps to discover printers and send data to EPSON ePOS.
version: 1.0.0
repository: https://github.com/mthuong/flutter_epson_epos
homepage: https://github.com/mthuong/flutter_epson_epos

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tlt.epson_epos
        pluginClass: EpsonEposPlugin
      ios:
        pluginClass: EpsonEposPlugin
