enum EpsonEPOSPortType {
  ALL(0), TCP(1), BLUETOOTH(2), USB(3), BLE_LE(4);
  final int value;

  const EpsonEPOSPortType(this.value);
}

enum EpsonEPOSPrintLang {
  MODEL_ANK,
  MODEL_CHINESE,
  MODEL_TAIWAN,
  MODEL_KOREAN,
  MODEL_THAI,
  MODEL_SOUTHASIA
}

enum EpsonEPOSCut { CUT_FEED, CUT_NO_FEED, CUT_RESERVE }

enum EpsonEPOSTextAlign { LEFT, CENTER, RIGHT }

enum EpsonEPOSFont { FONT_A, FONT_B, FONT_C, FONT_D, FONT_E }

enum EpsonEPOSColor {
  COLOR_NONE,
  COLOR_1,
  COLOR_2,
  COLOR_3,
  COLOR_4,
}

enum Epos2Barcode {
  EPOS2_BARCODE_UPC_A(0),
  EPOS2_BARCODE_UPC_E(1),
  EPOS2_BARCODE_EAN13(2),
  EPOS2_BARCODE_JAN13(3),
  EPOS2_BARCODE_EAN8(4),
  EPOS2_BARCODE_JAN8(5),
  EPOS2_BARCODE_CODE39(6),
  EPOS2_BARCODE_ITF(7),
  EPOS2_BARCODE_CODABAR(8),
  EPOS2_BARCODE_CODE93(9),
  EPOS2_BARCODE_CODE128(10),
  EPOS2_BARCODE_GS1_128(11),
  EPOS2_BARCODE_GS1_DATABAR_OMNIDIRECTIONAL(12),
  EPOS2_BARCODE_GS1_DATABAR_TRUNCATED(13),
  EPOS2_BARCODE_GS1_DATABAR_LIMITED(14),
  EPOS2_BARCODE_GS1_DATABAR_EXPANDED(15),
  EPOS2_BARCODE_CODE128_AUTO(16);

  final int value;

  const Epos2Barcode(this.value);
}

enum Epos2Hri {
  EPOS2_HRI_NONE(0),
  EPOS2_HRI_ABOVE(1),
  EPOS2_HRI_BELOW(2),
  EPOS2_HRI_BOTH(3);

  final int value;

  const Epos2Hri(this.value);
}
